<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!-- Keep this the same as the TargetFramework in FilmStrip.vbproj (net48 works too). -->
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>FilmStripTest</RootNamespace>
    <AssemblyName>FilmStripTest</AssemblyName>
    <MyType>WindowsFormsWithCustomSubMain</MyType>
    <StartupObject>FilmStripTest.Program</StartupObject>
    <OptionExplicit>On</OptionExplicit>
    <OptionStrict>On</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <OptionCompare>Binary</OptionCompare>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FilmStrip\FilmStrip.vbproj" />
  </ItemGroup>

</Project>
